name: Releases

on:
  push:
    branches:
      - main
#  pull_request:
#    tags:
#      - '*'

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: release
        uses: rymndhng/release-on-push-action@master

