name: Releases

on:
  push:
    branches:
      - main
#  pull_request:
#    tags:
#      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # (Required!) The GitHub token
#          tag: ${{ github.ref }}
#          artifacts: "release.tar.gz,foo/*.txt"
          bodyFile: "README.md"

